version: "3.8"

services:
  fastapi-service:
    container_name: fastapi-sudoku-app-container

    image: takanarishimbo/fastapi-sudoku-app:v1.0.0

    ports:
      - "${SERVER_PORT}:8000"

    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

    restart: always
